DROP TABLE Galaktyka cascade constraints;
DROP SEQUENCE Galaktyka_seq;
DROP TABLE Narzedzie_odkrywcze cascade constraints;
DROP SEQUENCE Narzedzie_odkrywcze_seq;
DROP TABLE Kraj cascade constraints;
DROP SEQUENCE Kraj_seq;
DROP TABLE Miasto cascade constraints;
DROP SEQUENCE Miasto_seq;
DROP TABLE Adres cascade constraints;
DROP SEQUENCE Adres_seq;
DROP TABLE Centrum_badawcze cascade constraints;
DROP SEQUENCE Centrum_badawcze_seq;
DROP TABLE Badacz cascade constraints;
DROP SEQUENCE Badacz_seq;
DROP TABLE Gwiazda cascade constraints;
DROP SEQUENCE Gwiazda_seq;
DROP TABLE Planeta cascade constraints;
DROP SEQUENCE Planeta_seq;
DROP TABLE HISTORIA_ADRESOW cascade constraints;
DROP TABLE HISTORIA_CENTROW cascade constraints;
DROP TABLE HISTORIA_BADACZY cascade constraints;
DROP TABLE HISTORIA_GALAKTYK cascade constraints;
DROP TABLE HISTORIA_GWIAZD cascade constraints;
DROP TABLE HISTORIA_KRAJOW cascade constraints;
DROP TABLE HISTORIA_MIAST cascade constraints;
DROP TABLE HISTORIA_NARZEDZI cascade constraints;
DROP TABLE HISTORIA_PLANET cascade constraints;
DROP SEQUENCE HISTORIA_ADRESOW_seq;
DROP SEQUENCE HISTORIA_CENTROW_seq;
DROP SEQUENCE HISTORIA_BADACZY_seq;
DROP SEQUENCE HISTORIA_GALAKTYK_seq;
DROP SEQUENCE HISTORIA_GWIAZD_seq;
DROP SEQUENCE HISTORIA_KRAJOW_seq;
DROP SEQUENCE HISTORIA_NARZEDZI_seq;
DROP SEQUENCE HISTORIA_PLANET_seq;
DROP SEQUENCE HISTORIA_MIAST_seq;
DROP VIEW Administrator_badacz_view;
DROP VIEW Badacz_badacz_view;
DROP VIEW Uzytkownik_badacz_view;
DROP VIEW Gwiazda_wszystko_view;
DROP VIEW Gwiazda_odkrywca_view;
DROP VIEW Gwiazda_narzedzie_view;
DROP VIEW Gwiazda_z_planeta_view;
